### ISSUE TITLE
Slow first load

### ISSUE THREAD

**Issue by lastgleam** [nogahighland/confluence-pagetree-search#6]
# Summary
This loads all the nodes in tree div at once.
It takes too much time to see meaningful content.

# Problems
All elements are loaded in tree div at the same time when user access a page. (Eager Loading)
`querySelector()` and `querySelectorAll()` are used a lot.

# Try to
Refactor to use lazy loading.
Refactor to use `getElementsByClassName()` and `getElementsByTagName()`.

**Comment by nogahighland** [comment]
Tree rendering feature is discarded in v2.0.0. So let me close this issue.
